name: cache-testing

on: push

jobs:
  mavencache:
    runs-on: ubuntu-latest


    steps:
      - name: test
        run: |
          echo $(java --version)
          echo $(mvn --version)
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
