name: cache-testing

on: push

jobs:
  mavencache:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
                
      - name: Cache local Maven repository
        uses: actions/cache/restore@v2
        id: maven-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: is miss ?
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: echo "miss hit"
        
      - name: is hit ?
        if: steps.maven-cache.outputs.cache-hit == 'true'
        run: echo "hit"

      - uses: actions/cache/save@v2
        with:
          path: ~/.m2/repository
          key: ${{ steps.maven-cache.outputs.cache-primary-key }}
