name: cache-testing

on: push

jobs:
  mavencache:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      
      - name: test
        run: |
          echo $(ngrok --version)
          
      - name: cache ngrok
        uses: actions/cache@v2
        id: cache
        with:
          key: ${{ runner.os }}-ngrok-10
          
      - name: check if already cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo snap install ngrok
      
      - name: checked install ngrok version
        run: |
          echo "is cached hit = " ${{steps.cache-ngrok-outputs.cache-hit}}
          echo $(ngrok --version)
