name: cache-testing

on: push

jobs:
  mavencache:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      
      - name: test
        run: |
          echo $(ngrok --version)
          
      - name: cache ngrok
        uses: actions/cache/restore@v2
        id: cache
        with:
          path: ~/
          key: ${{ runner.os }}-ngrok-10
          
      - name: check if already cached
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: echo ${{ steps.cache.outputs.cache-hit }}
      
      # - name: checked install ngrok version
      #   run: |
      #     echo "is cached hit = " ${{ runner.os }}
      #     echo $(ngrok --version)
