name: cache-testing

on: push

jobs:
  mavencache:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      
      - name: test
        run: |
          echo $(ngrok --version)
          
      - name: cache ngrok
        uses: actions/cache/@v2
        id: cache-ngrok
        with:
          path: ~/snap/ngrok
          key: ${{ runner.os }}-ngrok-2
          
      - name: check if already cached
        if: steps.cache-ngrok-outputs.cache-hit != 'true'
        run: sudo snap install ngrok
      
      - name: checked install ngrok version
        run: |
          echo $(ngrok --version)
