name: savingsTest

on: push

jobs:
  mavencache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        id: maven-cache
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
        
      # - name: Cache local Maven repository
        # uses: actions/cache@v2
        # id: maven-cache
        # with:
          # path: ~/.m2/repository
          # key: setup-java-Linux-maven-${{ hashFiles('**/pom.xml') }}
          # restore-keys: |
            # ${{ runner.os }}-maven-

      - name: is miss ?
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: echo "miss"
        
      - name: is hit ?
        if: steps.maven-cache.outputs.cache-hit == 'true'
        run: echo "hit"
          # chmod +x integration-test-web-admin-control.sh
          # ./integration-test-web-admin-control.sh

      - name: java installed ?
        run: |
          echo java --version
          echo mvn --version
